### ISSUE TITLE
Not Redstone

### ISSUE THREAD

**Issue by ArturilloD** [Lolcroc/ProjectLepton#6] opened 2020-08-27 16:59 UTC
Hi, I would like to know how I can disable the redstone. Can you help me please?

**Comment by mont-40** [comment] 2020-09-09 14:11
This is not a feature. What do you mean exactly with disable?

**Comment by ArturilloD** [comment] 2020-09-10 03:44
Good, yes, what I wanted to say is if there is any possibility of adding a
button to be able to activate or deactivate the redstone and continue
crafting without the signal pulse, since it generates a lot of lag. Thank
you

**Comment by mont-40** [comment] 2020-09-10 09:26
Lots of redstone dust is infamous for lag. In the redstone community it is very common for large machines to be made entirely of other components such as observers, repeaters, etc. How much dust do you use and have you tried making your clocks without it?

**Comment by ArturilloD** [comment] 2020-09-10 10:15
In fact, I only used two observers in a test with 10 redstone powders,
which was the worst because of the lag and in the other I only used
observers, there was much better lag

**Comment by mont-40** [comment] 2020-09-10 12:25
So is it still really a problem without the dust?

**Comment by ArturilloD** [comment] 2020-09-10 13:10
Yes, exactly

**Comment by mont-40** [comment] 2020-09-10 16:15
So then the lag is probably coming from the automat itself. I will benchmark the lag from the automat for the next version

**Comment by ArturilloD** [comment] 2020-09-10 20:23
Well thanks. Anything you need advise

**Comment by mont-40** [comment] 2022-01-15 00:51
Duplicate of #16. Closing for now

**Closed as completed by mont-40** 2022-01-15 00:51 UTC
Labels: enhancement
