### ISSUE TITLE
Crafting rockets

### ISSUE THREAD

**Issue by manzipan** [Lolcroc/ProjectLepton#12] opened 2021-02-06 11:04 UTC
very nice mod i use it on server with 1.16.5 only issue im getting is i cannot autocraft rockets which is the reason i downloaded this mod the recipie shows up on the crafting i can manualy craft it but no autocrafting is there a way to fix this

**Comment by mont-40** [comment] 2021-02-08 19:42
No unfortunately you can't for rockets, books, maps, etc. So sorry you can't use this mod but it's planned for next versions

**Comment by mont-40** [comment] 2022-01-15 00:48
Duplicate of #10. Closing this issue for now

**Closed as completed by mont-40** 2022-01-15 00:48 UTC
Labels: enhancement
